name: ci

on:
  push:
    branches:
      - main
      - beta
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 12

jobs:
  install-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm latest
        run: npm i -g npm@latest --registry=https://registry.npmjs.org
      - name: Cache dependencies
        uses: actions/cache@v2
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Install Dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          npm install
  format:
    runs-on: ubuntu-latest
    needs: install-cache
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm latest
        run: npm i -g npm@latest --registry=https://registry.npmjs.org
      - name: Restore dependencies
        uses: actions/cache@v2
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Run prettier
        run: |
          npm run format:check
  build:
    runs-on: ubuntu-latest
    needs: format
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm latest
        run: npm i -g npm@latest --registry=https://registry.npmjs.org
      - name: Restore dependencies
        uses: actions/cache@v2
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Run build
        run: |
          npm run build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-output
          path: |
            ./packages/all/dist
            ./packages/graph/dist
            ./packages/react/dist
          retention-days: 1
  unit-test-scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm latest
        run: npm i -g npm@latest --registry=https://registry.npmjs.org
      - name: Restore dependencies
        uses: actions/cache@v2
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-output
          path: packages
      - name: Run tests
        run: |
          npm run test
      # Scan done here so we have the test reports
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}
  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm latest
        run: npm i -g npm@latest --registry=https://registry.npmjs.org
      - name: Restore dependencies
        uses: actions/cache@v2
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-output
          path: packages
      - name: Run lint
        run: |
          npm run lint
  build-example:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm latest
        run: npm i -g npm@latest --registry=https://registry.npmjs.org
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-output
          path: packages
      - name: Restore dependencies
        uses: actions/cache@v2
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Check example
        run: |
          npm install
          npm run build
        working-directory: ./example
  build-storybook:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm latest
        run: npm i -g npm@latest --registry=https://registry.npmjs.org
      - name: Restore dependencies
        uses: actions/cache@v2
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Build Storybook
        run: npm run storybook:build --quiet
  release:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/beta'
    runs-on: ubuntu-latest
    needs: [build, build-example]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm latest
        run: npm i -g npm@latest --registry=https://registry.npmjs.org
      - name: Restore dependencies
        uses: actions/cache@v2
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-output
          path: packages
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: commitd-bot
          GIT_AUTHOR_EMAIL: 56758001+committed-bot@users.noreply.github.com
          GIT_COMMITTER_NAME: commitd-bot
          GIT_COMMITTER_EMAIL: 56758001+commitd-bot@users.noreply.github.com
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run semantic-release
  publish-storybook:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm latest
        run: npm i -g npm@latest --registry=https://registry.npmjs.org
      - name: Restore dependencies
        uses: actions/cache@v2
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Publish Storybook
        if: github.ref == 'refs/heads/main'
        run: npm run storybook:deploy
        env:
          GH_TOKEN: commitd-bot:${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
