name: ci

on:
  push:
    branches:
      - main
      - beta
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 16

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: ${{ env.NODE_VERSION }}
      - name: Install Dependencies
        run: |
          npm ci
      - name: build
        run: |
          npm run ci
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-output
          path: |
            ./packages/all/dist
            ./packages/graph/dist
            ./packages/graph-rdf/dist
            ./packages/graph-json/dist
            ./packages/react/dist
          retention-days: 1
  release:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/beta'
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: ${{ env.NODE_VERSION }}
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-output
          path: packages
      - name: Install Dependencies
        run: |
          npm ci
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: commitd-bot
          GIT_AUTHOR_EMAIL: 56758001+committed-bot@users.noreply.github.com
          GIT_COMMITTER_NAME: commitd-bot
          GIT_COMMITTER_EMAIL: 56758001+commitd-bot@users.noreply.github.com
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run semantic-release
      - name: Publish Storybook
        if: github.ref == 'refs/heads/main'
        run: npm run storybook:deploy
        env:
          GH_TOKEN: commitd-bot:${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
